In [1]:
from scipy import linalg
import numpy as np
import pandas as pd
import math
from math import sqrt

np.set_printoptions(precision=4, suppress=True)
pd.set_option('display.float_format', lambda x: '%.3f' % x)

### P6 - 12 b

In [2]:
def show(name, element):
    print(name, '=')
    print(element)
    print()

def svd(A):
    show('A', A)
    At_A = A.transpose() @ A
    show('At A  =', At_A)
    sigmas_squared, eigenvectors = np.linalg.eig(At_A)
    show('sigmas squared', sigmas_squared)
    show('eigenvectors of At A', eigenvectors)
    singular_values = sorted(math.sqrt(sigma_squared) for sigma_squared in sigmas_squared)
    show('singular values of A', [round(n, 2) for n in singular_values])
    V = np.array([])
    
A = np.array([[1, -2], [-1, 2], [1, 4]])
svd(A)

A =
[[ 1 -2]
 [-1  2]
 [ 1  4]]

At A  = =
[[ 3  0]
 [ 0 24]]

sigmas squared =
[  3.  24.]

eigenvectors of At A =
[[ 1.  0.]
 [ 0.  1.]]

singular values of A =
[1.73, 4.9]



In [3]:
math.sqrt(24), math.sqrt(3)

(4.898979485566356, 1.7320508075688772)

In [13]:
1/sqrt(42)
1/(2*sqrt(6))

0.20412414523193154

In [14]:
U, sigmas, V = linalg.svd(A)

In [15]:
U

array([[ 0.4082, -0.5774, -0.7071],
       [-0.4082,  0.5774, -0.7071],
       [-0.8165, -0.5774, -0.    ]])

In [17]:
my_U

array([[-0.4082,  0.5774,  0.7071],
       [ 0.4082, -0.5774,  0.7071],
       [ 0.8165,  0.5774,  0.    ]])

In [31]:
m, n = (2, 3)
sigma = np.zeros((m, n))
sigma_pinv = np.zeros((n, m))

for i in range(min(m, n)):
    sigma[i, i] = sigmas[i]
    sigma_pinv[i, i] = 1/sigmas[i]

sigma_pinv

array([[ 0.2041,  0.    ],
       [ 0.    ,  0.5774],
       [ 0.    ,  0.    ]])

In [16]:
my_U = np.array([
        [-1/sqrt(6), 1/sqrt(6), 2/sqrt(6)],
        [1/sqrt(3), -1/sqrt(3), 1/sqrt(3)],
        [1/sqrt(2), 1/sqrt(2), 0]
    ]).transpose()

U.transpose() @ U

array([[ 1., -0.,  0.],
       [-0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [9]:
np.linalg.pinv(A)

array([[ 0.3333, -0.3333,  0.3333],
       [-0.0833,  0.0833,  0.1667]])

A = np.array([[1, -1], [-2, 2], [2, -2]])
A.transpose() @ A

In [35]:
np.linalg.pinv(np.array([[1, 1], [2, 2]]))

array([[ 0.1,  0.2],
       [ 0.1,  0.2]])

In [34]:
A = np.array([
        [1, 2], [0, 3]
    ])

A.transpose() @ A

array([[ 1,  2],
       [ 2, 13]])

In [36]:
A = np.array([[1, -2], [-1, 2], [1, 4]])
A_pinv = np.linalg.pinv(A)
A_pinv

array([[ 0.3333, -0.3333,  0.3333],
       [-0.0833,  0.0833,  0.1667]])

0.16666666666666666